apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: orixa-admin-frontend
  namespace: orixa
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: admin.orixa.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: orixa-admin-frontend
                port:
                  number: 80
